### ISSUE TITLE
Check the difference with sinpro-dev

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-template-for-sveltekit#23]
# Tasks

- [x] [対応表](https://docs.google.com/spreadsheets/d/1REZlXMy67XGSBubbESUxfwXGV54So5r7FYwZZDd69bI/edit#gid=0)で確認する
- [x] sinpro.dev とのコードの差分で確認する
- [x] #29

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [ ] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [ ] Insure that changes include only what is necessary for this PR
- [ ] Implement necessary Unit tests
- [ ] Implement necessary E2E tests
- [ ] Perform functionality checks
