### ISSUE TITLE
Configure Test Coverage

### ISSUE THREAD

**Issue by sinproject-iwasaki** [sinProject-Inc/sinpro-template-for-sveltekit#45]
# References

- [Vitest - Coverage](https://vitest.dev/guide/coverage.html)
- [SonarCloud - JavaScript/TypeScript Test Coverage](https://docs.sonarcloud.io/enriching/test-coverage/javascript-typescript-test-coverage/)

# Tasks

- [x] `npm i -D @vitest/coverage-v8`
- [x] Setup script on package.json
- [x] Configure vite.config.ts
- [x] Configure ignore files
- [x] Configure GitHub Actions
- [x] Configure GitHub Secrets
- [x] Configure sonarlint files

Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Share your screen on Discord
- [x] Write which issue you are starting on Slack
- [x] Git: Fetch the latest main
- [ ] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks
