### ISSUE TITLE
Update packeges with ncu

### ISSUE THREAD

**Issue by Acha0203** [sinProject-Inc/sinpro-template-for-sveltekit#68]
# Tasks

- [x] Update packeges with `ncu`
- [x] Run `npm audit fix` if necessary

Estimated Time: XXmin

# Writing the Issue

- [x] Write each task for this issue using checkboxes
- [x] Write all verbal instructions as tasks
- [x] Add labels and assignees

# Before Working on the Issue

- [x] Assign yourself
- [x] Git: Fetch the latest main
- [x] Git: Create a branch with the name of the issue

# Pre-PR Checks

- [x] Insure that changes include only what is necessary for this PR
- [x] Implement necessary Unit tests
- [x] Implement necessary E2E tests
- [x] Perform functionality checks

**Comment by Acha0203** [comment]
こちらの Issue に対応して push したところ、GitHub Actions でエラーがありました。

```
Run npx playwright test
[WebServer] 

Running 1 test using 1 worker
F

  1) test.spec.ts:3:1 › index page has expected h1 ─────────────────────────────────────────────────

    Error: browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1084/chrome-linux/chrome
    ╔══════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.39.0. ║
    ║ Please update docker image as well.                                  ║
    ║ -  current: mcr.microsoft.com/playwright:v1.38.0-jammy               ║
    ║ - required: mcr.microsoft.com/playwright:v1.39.0-jammy               ║
    ║                                                                      ║
    ║ <3 Playwright Team                                                   ║
    ╚══════════════════════════════════════════════════════════════════════╝




  1 failed
    test.spec.ts:3:1 › index page has expected h1 ──────────────────────────────────────────────────
Error: Process completed with exit code 1.
```

Playwrite をアップデートする必要があるようですが、別 Issue を立てて対応するべきでしょうか？

**Comment by iamsin** [comment]
@Acha0203 @REI-MORI 

この Issue で ci.yml を更新していただいて大丈夫です！
